  apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: subsonic-data 
    annotations:
      volume.beta.kubernetes.io/storage-class: "slow"
    labels:
      name: subsonic-data
  spec:
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /hyper-tank/subonic-data 
      server: 192.168.1.254 
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: subsonic-data-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: "subsonic-data"
